Name:           ros-jade-laser-geometry
Version:        1.6.4
Release:        0%{?dist}
Summary:        ROS laser_geometry package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/laser_geometry
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       eigen3-devel
Requires:       numpy
Requires:       ros-jade-angles
Requires:       ros-jade-roscpp
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-tf
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel
BuildRequires:  ros-jade-angles
BuildRequires:  ros-jade-catkin >= 0.5.68
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rosunit
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-tf

%description
This package contains a class for converting from a 2D laser scan as defined by
sensor_msgs/LaserScan into a point cloud as defined by sensor_msgs/PointCloud or
sensor_msgs/PointCloud2. In particular, it contains functionality to account for
the skew resulting from moving robots or tilting laser scanners.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon May 18 2015 Dave Hershberger <dave.hershberger@sri.com> - 1.6.4-0
- Autogenerated by Bloom

* Sun Mar 15 2015 Dave Hershberger <dave.hershberger@sri.com> - 1.6.3-0
- Autogenerated by Bloom

